use_frameworks!

platform :ios, '10.0'

target 'UncleThird_Example' do
  pod 'UncleThird', :path => '../'

  target 'UncleThird_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
